export const surahAudioLinks = [
    { surahId: 1,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/ZYaZ6Odbx_Y` }] },
    { surahId: 2,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/8x_URBJW5Dk` }, {name:'Audio 2', link:`https://www.youtube.com/embed/Isi5PJVN9S0`}] },
    { surahId: 3,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/mNqoSW_5SmA` }, { name: 'Audio 2', link: `https://www.youtube.com/embed/D5pWGzYBrXc` }] },
    { surahId: 4,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fMo163Ya3SY` }, {name:'Audio 2', link:"https://www.youtube.com/embed/1fCtE2E4IUs"}] },
    { surahId: 5,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/9zqVkeoAP7U` }, {name:"Audio 2", link:"https://www.youtube.com/embed/s44-9C7EhjE"}] },
    { surahId: 6,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/liK3RH8f8QA` }, {name:"Audio 2", link:'https://www.youtube.com/embed/XZyp3v6BFgc'}] },
    { surahId: 7,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/_JFNbs6IUgU` },{name:"Audio 2", link:'https://www.youtube.com/embed/oC1XFJ5Q9nE'}] },
    { surahId: 8,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/3fDDtUnvta8` },{name:"Audio 2", link:'https://www.youtube.com/embed/x1eBFad2baI'}] },
    { surahId: 9,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/QJVuFqXxLo4` },{name:"Audio 2", link:'https://www.youtube.com/embed/X6Mff6eCWcs'}] },
    { surahId: 10, links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/kObPjzn_H5c` },{name:"Audio 2", link:'https://www.youtube.com/embed/UTIDryXbyoI'}] },
    { surahId: 11, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Cs24aEm0q3o` },{name:'Audio 2', link:'https://www.youtube.com/embed/KT7PAnrw4Os'}] },
    { surahId: 12, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/oTRSrJM0WAM` },{name:'Audio 2', link:'https://www.youtube.com/embed/zONfmm_magI'}] },
    { surahId: 13, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gfAdREN1SL8` },{name:'Audio 2', link:'https://www.youtube.com/embed/3Ol6qfCD-YI'}] },
    { surahId: 14, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vH2AhmUSQ74` },{name:'Audio 2', link:'https://www.youtube.com/embed/dcBREXkZ4A8'}] },
    { surahId: 15, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/zevi4w8cv_0` },{name:'Audio 2', link:'https://www.youtube.com/embed/EQ7PJGd7ePk'}] },
    { surahId: 16, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/jw_MvrLWJ6A` },{name:'Audio 2', link:'https://www.youtube.com/embed/3-qetiJ8xBo'}] },
    { surahId: 17, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/OJccFa-kVfM` },{name:'Audio 2', link:'https://www.youtube.com/embed/m9TLWVly3-o'}] },
    { surahId: 18, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ozHal4UUXl0` },{name:'Audio 2', link:'https://www.youtube.com/embed/pzjDCuvJIKw'}] },
    { surahId: 19, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/huSrUH-spDw` },{name:'Audio 2', link:'https://www.youtube.com/embed/JNlb3TA_6JM'}] },
    { surahId: 20, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/pn7pwU7U-kk` },{name:'Audio 2', link:'https://www.youtube.com/embed/aMh21G723_M'}] },
    { surahId: 21, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/NUIKzCabZfA` },{name:'Audio 2', link:'https://www.youtube.com/embed/Bz7G3kfZRoo'}] },
    { surahId: 22, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/aXtz3-4EOds` },{name:'Audio 2', link:'https://www.youtube.com/embed/pqA-uIO9nUk'}] },
    { surahId: 23, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/D1RL-lQZuqQ` },{name:'Audio 2', link:'https://www.youtube.com/embed/RF-TSmICOFU'}] },
    { surahId: 24, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vzfITR_YabY` },{name:'Audio 2', link:'https://www.youtube.com/embed/CzN4-LPrIto'}] },
    { surahId: 25, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/mNbAc2ebg7A` },{name:'Audio 2', link:'https://www.youtube.com/embed/JJMHoOB2wMU'}] },
    { surahId: 26, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/4ZaPUeVM0tM` },{name:'Audio 2', link:'https://www.youtube.com/embed/P7WlEQea6bY'}] },
    { surahId: 27, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/LcKpQPK9QrE` },{name:'Audio 2', link:'https://www.youtube.com/embed/McX-sVZDB4s'}] },
    { surahId: 28, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/YJOFzpK4XTE` },{name:'Audio 2', link:'https://www.youtube.com/embed/o00zHESdboU'}] },
    { surahId: 29, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/z9fD6P4yhOs` },{name:'Audio 2', link:'https://www.youtube.com/embed/9s5pK4--YWw'}] },
    { surahId: 30, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/pXhar6aJmaY` },{name:'Audio 2', link:'https://www.youtube.com/embed/wlcLLZSP0aY'}] },
    { surahId: 31, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ND5QWd7MB70` },{name:'Audio 2', link:'https://www.youtube.com/embed/hr4wUD9QXqI'}] },
    { surahId: 32, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/NQ6hyyjlq7c` },{name:'Audio 2', link:'https://www.youtube.com/embed/A7tx_XUNuYk'}] },
    { surahId: 33, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vybruxcWZTs` },{name:'Audio 2', link:'https://www.youtube.com/embed/yn4p7JP1nxg'}] },
    { surahId: 34, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/atLcGsBXqdE` },{name:'Audio 2', link:'https://www.youtube.com/embed/irPfsxbO4C4'}] },
    { surahId: 35, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/DQKIBzLkkzc` },{name:'Audio 2', link:'https://www.youtube.com/embed/3Ftt-PoMsH4'}] },
    { surahId: 36, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Q9xYG8PLxeg` },{name:'Audio 2', link:'https://www.youtube.com/embed/Cz7k4MeByfw'}] },
    { surahId: 37, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Al0b4T3uqro` },{name:'Audio 2', link:'https://www.youtube.com/embed/zCgjoHHsAiQ'}] },
    { surahId: 38, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ZA4o73IpYFw` },{name:'Audio 2', link:'https://www.youtube.com/embed/Sa_ufMcyHiM'}] },
    { surahId: 39, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/HpiZrGTPGjw` },{name:'Audio 2', link:'https://www.youtube.com/embed/aFfMQ2ELTS0'}] },
    { surahId: 40, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fQfksWKINk4` },{name:'Audio 2', link:'https://www.youtube.com/embed/GYY_ULvGXYU'}] },
    { surahId: 41, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/R8f0vLjEw3Q` },{name:'Audio 2', link:'https://www.youtube.com/embed/D33ewkq0Y1A'}] },
    { surahId: 42, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Q8Q16INbLe8` },{name:'Audio 2', link:'https://www.youtube.com/embed/v1KsQBLpHFg'}] },
    { surahId: 43, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/K-DYuUuN61U` },{name:'Audio 2', link:'https://www.youtube.com/embed/I68Uy2WdPng'}] },
    { surahId: 44, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/QvLqDAECum8` },{name:'Audio 2', link:'https://www.youtube.com/embed/fxlbZHx0xN0'}] },
    { surahId: 45, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/v5ZW5Wd3hwY` },{name:'Audio 2', link:'https://www.youtube.com/embed/Aaxsla3SEVI'}] },
    { surahId: 46, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/FRbqhz12L9o` },{name:'Audio 2', link:'https://www.youtube.com/embed/lkehbYvHP7U'}] },
    { surahId: 47, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/yD7gNwi4esQ` },{name:'Audio 2', link:'https://www.youtube.com/embed/AE34p_jqr_k'}] },
    { surahId: 48, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/On9rhT1Iw0U` },{name:'Audio 2', link:'https://www.youtube.com/embed/KSgi5-S4g4Y'}] },
    { surahId: 49, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/viHOv8Hspis` },{name:'Audio 2', link:'https://www.youtube.com/embed/wq3awaYpH7w'}] },
    { surahId: 50, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/um7O7iuvXzY` },{name:'Audio 2', link:'https://www.youtube.com/embed/yV4ScDIQeFY'}] },
    { surahId: 51, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/kRrkXBdPLDQ` },{name:'Audio 2', link:'https://www.youtube.com/embed/byXxbILJUBo'}] },
    { surahId: 52, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/5SI5NAEbhbo` },{name:'Audio 2', link:'https://www.youtube.com/embed/egUXtr53fXk'}] },
    { surahId: 53, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/6eIPNa1VZyU` },{name:'Audio 2', link:'https://www.youtube.com/embed/eMKFoVtubN4'}] },
    { surahId: 54, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/C7tPyQVWh5Q` },{name:'Audio 2', link:'https://www.youtube.com/embed/Qppa350MFGQ'}] },
    { surahId: 55, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/q--zAOMtQE4` },{name:'Audio 2', link:'https://www.youtube.com/embed/8d-KAuPcuYI'}] },
    { surahId: 56, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/pRxe3IDhzWI` },{name:'Audio 2', link:'https://www.youtube.com/embed/6ZZwMqsYQnU'}] },
    { surahId: 57, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/amUiwxHQ8Iw` },{name:'Audio 2', link:'https://www.youtube.com/embed/VL6lTjN0x-U'}] },
    { surahId: 58, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/GaDJ8-BKqr0` },{name:'Audio 2', link:'https://www.youtube.com/embed/85lenZXNMnQ'}] },
    { surahId: 59, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/cbwec9puSug` },{name:'Audio 2', link:'https://www.youtube.com/embed/85lenZXNMnQ'}] },
    { surahId: 60, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gKB7TJ7_vNo` },{name:'Audio 2', link:'https://www.youtube.com/embed/-SMyaIuugt8'}] },
    { surahId: 61, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/2ermATsCofM` },{name:'Audio 2', link:'https://www.youtube.com/embed/Hders8i7Ky8'}] },
    { surahId: 62, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/kNS_xapmyWo` },{name:'Audio 2', link:'https://www.youtube.com/embed/zhJD2kgJf6g'}] },
    { surahId: 63, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/hcfHY0vPxXU` },{name:'Audio 2', link:'https://www.youtube.com/embed/PKK1l7Ai6Ao'}] },
    { surahId: 64, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ILfO_61wxqU` },{name:'Audio 2', link:'https://www.youtube.com/embed/OX81wxjEneg'}] },
    { surahId: 65, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/RO3JGHqieN0` },{name:'Audio 2', link:'https://www.youtube.com/embed/nPFbnZuYpNs'}] },
    { surahId: 66,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/eog2u7jigzo` },{name:'Audio 2', link:'https://www.youtube.com/embed/9ipAb38DcpY'}] },
    { surahId: 67,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/9WyZl9FxREY` },{name:'Audio 2', link:'https://www.youtube.com/embed/qOcSinjmJ2U'}] },
    { surahId: 68,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/otudaLjZBuY` },{name:'Audio 2', link:'https://www.youtube.com/embed/QhRM0Rf_a30'}] },
    { surahId: 69,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/FtsmJMz8AYw` },{name:'Audio 2', link:'https://www.youtube.com/embed/5GG1VOPQIyA'}] },
    { surahId: 70,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ai30YF3AGb4` },{name:'Audio 2', link:'https://www.youtube.com/embed/bWysVXUJfm8'}] },
    { surahId: 71,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/O61XEc4fBkY` }] },
    { surahId: 72,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/VhFW2th-iIo` }] },
    { surahId: 73,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/wawkeiueSBk` }] },
    { surahId: 74,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Nhl0AZQaa_g` }] },
    { surahId: 75,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/6evCVJmerJs` }] },
    { surahId: 76,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/QOUp0GmgCQg` }] },
    { surahId: 77,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Uc0XgRE7718` }] },
    { surahId: 78,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/uPI5vmuI8WY` }] },
    { surahId: 79,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/oyahCibEdVE` }] },
    { surahId: 80,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/K7H5DG5-6no` }] },
    { surahId: 81,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/2l5gZctbgcE` }] },
    { surahId: 82,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Y2NEO3LDec8` }] },
    { surahId: 83,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/3bVJMONwoAw` }] },
    { surahId: 84,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/cd4HW9rJLpI` }] },
    { surahId: 85,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/UZvJebrIQfk` }] },
    { surahId: 86,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/LLXn-kE-598` }] },
    { surahId: 87,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/67gs-vCBaYI` }] },
    { surahId: 88,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vfoom6l6L4w` }] },
    { surahId: 89,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/72XHGhLre_8` }] },
    { surahId: 90,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/PlXaz9onniw` }] },
    { surahId: 91,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fIYk6ioKPDM` }] },
    { surahId: 92,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/_pMLBImgEvk` }] },
    { surahId: 93,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/r3wCitqDxF8` }] },
    { surahId: 94,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/59snlUGtDmQ` }] },
    { surahId: 95,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/tHy1k14w9xk` }] },
    { surahId: 96,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/JZ_yfEoJf6M` }] },
    { surahId: 97,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/VLDvWxqUK7A` }] },
    { surahId: 98,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/U-1bn6IisXg` }] },
    { surahId: 99,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/AwCQfhh_Sh8` }] },
    { surahId: 100, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/YaOZS4ZoRY8` }] },
    { surahId: 101, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gmdTyUr4DzA` }] },
    { surahId: 102, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/mkOwo41gkp8` }] },
    { surahId: 103, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/-I2RkWeQvuo` }] },
    { surahId: 104, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/rnST2MaCjrY` }] },
    { surahId: 105, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/4C3FZjkIKKo` }] },
    { surahId: 106, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/wktEC7Jp5CU` }] },
    { surahId: 107, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/l8VF5p4oPDE` }] },
    { surahId: 108, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gguAmbBNhJQ` }] },
    { surahId: 109, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/4CvUCt_7t9Y` }] },
    { surahId: 110, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/MVE1Mozt23w` }] },
    { surahId: 111, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/M3dBqRX32fI` }] },
    { surahId: 112, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fyub76Z1YW8` }] },
    { surahId: 113, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/MaOepE0iVP0` }] },
    { surahId: 114, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/5UTXy190B-I` }] }       
];
