export const surahAudioLinks = [
    { surahId: 1,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/ZYaZ6Odbx_Y` }] },
    { surahId: 2,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/8x_URBJW5Dk` }, {name:'Audio 2', link:`https://www.youtube.com/embed/Isi5PJVN9S0`}] },
    { surahId: 3,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/mNqoSW_5SmA` }, { name: 'Audio 2', link: `https://www.youtube.com/embed/D5pWGzYBrXc` }] },
    { surahId: 4,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fMo163Ya3SY` }, {name:'Audio 2', link:"https://www.youtube.com/embed/1fCtE2E4IUs"}] },
    { surahId: 5,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/9zqVkeoAP7U` }, {name:"Audio 2", link:"https://www.youtube.com/embed/s44-9C7EhjE"}] },
    { surahId: 6,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/liK3RH8f8QA` }, {name:"Audio 2", link:'https://www.youtube.com/embed/XZyp3v6BFgc'}] },
    { surahId: 7,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/_JFNbs6IUgU` },{name:"Audio 2", link:'https://www.youtube.com/embed/oC1XFJ5Q9nE'}] },
    { surahId: 8,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/3fDDtUnvta8` },{name:"Audio 2", link:'https://www.youtube.com/embed/x1eBFad2baI'}] },
    { surahId: 9,  links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/QJVuFqXxLo4` },{name:"Audio 2", link:'https://www.youtube.com/embed/X6Mff6eCWcs'}] },
    { surahId: 10, links: [
        { name: 'Audio 1', link: `https://www.youtube.com/embed/kObPjzn_H5c` },{name:"Audio 2", link:'https://www.youtube.com/embed/UTIDryXbyoI'}] },
    { surahId: 11, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Cs24aEm0q3o` },{name:'Audio 2', link:'https://www.youtube.com/embed/KT7PAnrw4Os'}] },
    { surahId: 12, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/oTRSrJM0WAM` },{name:'Audio 2', link:'https://www.youtube.com/embed/zONfmm_magI'}] },
    { surahId: 13, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gfAdREN1SL8` },{name:'Audio 2', link:'https://www.youtube.com/embed/3Ol6qfCD-YI'}] },
    { surahId: 14, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vH2AhmUSQ74` },{name:'Audio 2', link:'https://www.youtube.com/embed/dcBREXkZ4A8'}] },
    { surahId: 15, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/zevi4w8cv_0` },{name:'Audio 2', link:'https://www.youtube.com/embed/EQ7PJGd7ePk'}] },
    { surahId: 16, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/jw_MvrLWJ6A` },{name:'Audio 2', link:'https://www.youtube.com/embed/3-qetiJ8xBo'}] },
    { surahId: 17, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/OJccFa-kVfM` },{name:'Audio 2', link:'https://www.youtube.com/embed/m9TLWVly3-o'}] },
    { surahId: 18, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ozHal4UUXl0` },{name:'Audio 2', link:'https://www.youtube.com/embed/pzjDCuvJIKw'}] },
    { surahId: 19, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/huSrUH-spDw` },{name:'Audio 2', link:'https://www.youtube.com/embed/JNlb3TA_6JM'}] },
    { surahId: 20, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/pn7pwU7U-kk` },{name:'Audio 2', link:'https://www.youtube.com/embed/aMh21G723_M'}] },
    { surahId: 21, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/NUIKzCabZfA` },{name:'Audio 2', link:'https://www.youtube.com/embed/Bz7G3kfZRoo'}] },
    { surahId: 22, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/aXtz3-4EOds` },{name:'Audio 2', link:'https://www.youtube.com/embed/pqA-uIO9nUk'}] },
    { surahId: 23, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/D1RL-lQZuqQ` },{name:'Audio 2', link:'https://www.youtube.com/embed/RF-TSmICOFU'}] },
    { surahId: 24, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vzfITR_YabY` },{name:'Audio 2', link:'https://www.youtube.com/embed/CzN4-LPrIto'}] },
    { surahId: 25, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/mNbAc2ebg7A` },{name:'Audio 2', link:'https://www.youtube.com/embed/JJMHoOB2wMU'}] },
    { surahId: 26, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/4ZaPUeVM0tM` },{name:'Audio 2', link:'https://www.youtube.com/embed/P7WlEQea6bY'}] },
    { surahId: 27, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/LcKpQPK9QrE` },{name:'Audio 2', link:'https://www.youtube.com/embed/McX-sVZDB4s'}] },
    { surahId: 28, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/YJOFzpK4XTE` },{name:'Audio 2', link:'https://www.youtube.com/embed/o00zHESdboU'}] },
    { surahId: 29, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/z9fD6P4yhOs` },{name:'Audio 2', link:'https://www.youtube.com/embed/9s5pK4--YWw'}] },
    { surahId: 30, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/pXhar6aJmaY` },{name:'Audio 2', link:'https://www.youtube.com/embed/wlcLLZSP0aY'}] },
    { surahId: 31, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ND5QWd7MB70` },{name:'Audio 2', link:'https://www.youtube.com/embed/hr4wUD9QXqI'}] },
    { surahId: 32, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/NQ6hyyjlq7c` },{name:'Audio 2', link:'https://www.youtube.com/embed/A7tx_XUNuYk'}] },
    { surahId: 33, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vybruxcWZTs` },{name:'Audio 2', link:'https://www.youtube.com/embed/yn4p7JP1nxg'}] },
    { surahId: 34, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/atLcGsBXqdE` },{name:'Audio 2', link:'https://www.youtube.com/embed/irPfsxbO4C4'}] },
    { surahId: 35, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/DQKIBzLkkzc` },{name:'Audio 2', link:'https://www.youtube.com/embed/3Ftt-PoMsH4'}] },
    { surahId: 36, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Q9xYG8PLxeg` },{name:'Audio 2', link:'https://www.youtube.com/embed/Cz7k4MeByfw'}] },
    { surahId: 37, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Al0b4T3uqro` },{name:'Audio 2', link:'https://www.youtube.com/embed/zCgjoHHsAiQ'}] },
    { surahId: 38, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ZA4o73IpYFw` },{name:'Audio 2', link:'https://www.youtube.com/embed/Sa_ufMcyHiM'}] },
    { surahId: 39, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/HpiZrGTPGjw` },{name:'Audio 2', link:'https://www.youtube.com/embed/aFfMQ2ELTS0'}] },
    { surahId: 40, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fQfksWKINk4` },{name:'Audio 2', link:'https://www.youtube.com/embed/GYY_ULvGXYU'}] },
    { surahId: 41, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/R8f0vLjEw3Q` },{name:'Audio 2', link:'https://www.youtube.com/embed/D33ewkq0Y1A'}] },
    { surahId: 42, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Q8Q16INbLe8` },{name:'Audio 2', link:'https://www.youtube.com/embed/v1KsQBLpHFg'}] },
    { surahId: 43, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/K-DYuUuN61U` },{name:'Audio 2', link:'https://www.youtube.com/embed/I68Uy2WdPng'}] },
    { surahId: 44, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/QvLqDAECum8` },{name:'Audio 2', link:'https://www.youtube.com/embed/fxlbZHx0xN0'}] },
    { surahId: 45, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/v5ZW5Wd3hwY` },{name:'Audio 2', link:'https://www.youtube.com/embed/Aaxsla3SEVI'}] },
    { surahId: 46, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/FRbqhz12L9o` },{name:'Audio 2', link:'https://www.youtube.com/embed/lkehbYvHP7U'}] },
    { surahId: 47, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/yD7gNwi4esQ` },{name:'Audio 2', link:'https://www.youtube.com/embed/AE34p_jqr_k'}] },
    { surahId: 48, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/On9rhT1Iw0U` },{name:'Audio 2', link:'https://www.youtube.com/embed/KSgi5-S4g4Y'}] },
    { surahId: 49, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/viHOv8Hspis` },{name:'Audio 2', link:'https://www.youtube.com/embed/wq3awaYpH7w'}] },
    { surahId: 50, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/um7O7iuvXzY` },{name:'Audio 2', link:'https://www.youtube.com/embed/yV4ScDIQeFY'}] },
    { surahId: 51, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/kRrkXBdPLDQ` },{name:'Audio 2', link:'https://www.youtube.com/embed/byXxbILJUBo'}] },
    { surahId: 52, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/5SI5NAEbhbo` },{name:'Audio 2', link:'https://www.youtube.com/embed/egUXtr53fXk'}] },
    { surahId: 53, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/6eIPNa1VZyU` },{name:'Audio 2', link:'https://www.youtube.com/embed/eMKFoVtubN4'}] },
    { surahId: 54, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/C7tPyQVWh5Q` },{name:'Audio 2', link:'https://www.youtube.com/embed/Qppa350MFGQ'}] },
    { surahId: 55, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/q--zAOMtQE4` },{name:'Audio 2', link:'https://www.youtube.com/embed/8d-KAuPcuYI'}] },
    { surahId: 56, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/pRxe3IDhzWI` },{name:'Audio 2', link:'https://www.youtube.com/embed/6ZZwMqsYQnU'}] },
    { surahId: 57, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/amUiwxHQ8Iw` },{name:'Audio 2', link:'https://www.youtube.com/embed/VL6lTjN0x-U'}] },
    { surahId: 58, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/GaDJ8-BKqr0` },{name:'Audio 2', link:'https://www.youtube.com/embed/85lenZXNMnQ'}] },
    { surahId: 59, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/cbwec9puSug` },{name:'Audio 2', link:'https://www.youtube.com/embed/85lenZXNMnQ'}] },
    { surahId: 60, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gKB7TJ7_vNo` },{name:'Audio 2', link:'https://www.youtube.com/embed/-SMyaIuugt8'}] },
    { surahId: 61, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/2ermATsCofM` },{name:'Audio 2', link:'https://www.youtube.com/embed/Hders8i7Ky8'}] },
    { surahId: 62, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/kNS_xapmyWo` },{name:'Audio 2', link:'https://www.youtube.com/embed/zhJD2kgJf6g'}] },
    { surahId: 63, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/hcfHY0vPxXU` },{name:'Audio 2', link:'https://www.youtube.com/embed/PKK1l7Ai6Ao'}] },
    { surahId: 64, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ILfO_61wxqU` },{name:'Audio 2', link:'https://www.youtube.com/embed/OX81wxjEneg'}] },
    { surahId: 65, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/RO3JGHqieN0` },{name:'Audio 2', link:'https://www.youtube.com/embed/nPFbnZuYpNs'}] },
    { surahId: 66,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/eog2u7jigzo` },{name:'Audio 2', link:'https://www.youtube.com/embed/9ipAb38DcpY'}] },
    { surahId: 67,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/9WyZl9FxREY` },{name:'Audio 2', link:'https://www.youtube.com/embed/qOcSinjmJ2U'}] },
    { surahId: 68,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/otudaLjZBuY` },{name:'Audio 2', link:'https://www.youtube.com/embed/QhRM0Rf_a30'}] },
    { surahId: 69,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/FtsmJMz8AYw` },{name:'Audio 2', link:'https://www.youtube.com/embed/5GG1VOPQIyA'}] },
    { surahId: 70,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/ai30YF3AGb4` },{name:'Audio 2', link:'https://www.youtube.com/embed/bWysVXUJfm8'}] },
    { surahId: 71,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/O61XEc4fBkY` },{name:"Audio 2", link:'https://www.youtube.com/embed/YwVSU8u67ns'}] },
    { surahId: 72,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/VhFW2th-iIo` },{name:"Audio 2", link:'https://www.youtube.com/embed/gSYZCOaPcx0'}] },
    { surahId: 73,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/wawkeiueSBk` },{name:"Audio 2", link:'https://www.youtube.com/embed/nnRKwEcbkoA'}] },
    { surahId: 74,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Nhl0AZQaa_g` },{name:"Audio 2", link:'https://www.youtube.com/embed/rgNoOL9T6Fw'}] },
    { surahId: 75,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/6evCVJmerJs` },{name:"Audio 2", link:'https://www.youtube.com/embed/4YBjMeW31H4'}] },
    { surahId: 76,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/QOUp0GmgCQg` },{name:"Audio 2", link:'https://www.youtube.com/embed/ndip9QGf3BQ'}] },
    { surahId: 77,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Uc0XgRE7718` },{name:"Audio 2", link:'https://www.youtube.com/embed/Zilh2KNesns'}] },
    { surahId: 78,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/uPI5vmuI8WY` },{name:"Audio 2", link:'https://www.youtube.com/embed/vKdWswEz-m8'}] },
    { surahId: 79,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/oyahCibEdVE` },{name:"Audio 2", link:'https://www.youtube.com/embed/x62hKXPmQCc'}] },
    { surahId: 80,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/K7H5DG5-6no` },{name:"Audio 2", link:'https://www.youtube.com/embed/OrJHmCJ-dwE'}] },
    { surahId: 81,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/2l5gZctbgcE` },{name:"Audio 2", link:'https://www.youtube.com/embed/og52MSySiww'}] },
    { surahId: 82,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/Y2NEO3LDec8` },{name:"Audio 2", link:'https://www.youtube.com/embed/gW7jqdRmyx8'}] },
    { surahId: 83,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/3bVJMONwoAw` },{name:"Audio 2", link:'https://www.youtube.com/embed/VhxDVtfBkYE'}] },
    { surahId: 84,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/cd4HW9rJLpI` },{name:"Audio 2", link:'https://www.youtube.com/embed/DeVeAU-XXYs'}] },
    { surahId: 85,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/UZvJebrIQfk` },{name:"Audio 2", link:'https://www.youtube.com/embed/oo99cSdfZyw'}] },
    { surahId: 86,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/LLXn-kE-598` },{name:"Audio 2", link:'https://www.youtube.com/embed/U_frd_aD7kQ'}] },
    { surahId: 87,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/67gs-vCBaYI` },{name:"Audio 2", link:'https://www.youtube.com/embed/nEUHJtxqOhg'}] },
    { surahId: 88,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/vfoom6l6L4w` },{name:"Audio 2", link:'https://www.youtube.com/embed/e-mG4ahK0z8'}] },
    { surahId: 89,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/72XHGhLre_8` },{name:"Audio 2", link:'https://www.youtube.com/embed/IhD1lgUyz00'}] },
    { surahId: 90,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/PlXaz9onniw` },{name:"Audio 2", link:'https://www.youtube.com/embed/M9CFIOoBwHA'}] },
    { surahId: 91,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fIYk6ioKPDM` },{name:"Audio 2", link:'https://www.youtube.com/embed/yQWTKA2E8qk'}] },
    { surahId: 92,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/_pMLBImgEvk` },{name:"Audio 2", link:'https://www.youtube.com/embed/UV9z34cIAFE'}] },
    { surahId: 93,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/r3wCitqDxF8` },{name:"Audio 2", link:'https://www.youtube.com/embed/cSsmfwXxeQg'}] },
    { surahId: 94,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/59snlUGtDmQ` },{name:"Audio 2", link:'https://www.youtube.com/embed/CqEcGtVbLXk'}] },
    { surahId: 95,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/tHy1k14w9xk` },{name:"Audio 2", link:'https://www.youtube.com/embed/zF5feQtHIF4'}] },
    { surahId: 96,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/JZ_yfEoJf6M` },{name:"Audio 2", link:'https://www.youtube.com/embed/r6A2-A9lRsA'}] },
    { surahId: 97,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/VLDvWxqUK7A` },{name:"Audio 2", link:'https://www.youtube.com/embed/84UJI8pTN9U'}] },
    { surahId: 98,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/U-1bn6IisXg` },{name:"Audio 2", link:'https://www.youtube.com/embed/RZdvVHHHoIg'}] },
    { surahId: 99,  links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/AwCQfhh_Sh8` },{name:"Audio 2", link:'https://www.youtube.com/embed/NAdDZ1ziMdc'}] },
    { surahId: 100, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/YaOZS4ZoRY8` },{name:"Audio 2", link:'https://www.youtube.com/embed/B09ColKiR10'}] },
    { surahId: 101, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gmdTyUr4DzA` },{name:"Audio 2", link:'https://www.youtube.com/embed/JSAb_iPO3-4'}] },
    { surahId: 102, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/mkOwo41gkp8` },{name:"Audio 2", link:'https://www.youtube.com/embed/fmqYteWXcXM'}] },
    { surahId: 103, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/-I2RkWeQvuo` },{name:"Audio 2", link:'https://www.youtube.com/embed/d3oFVYhpozE'}] },
    { surahId: 104, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/rnST2MaCjrY` },{name:"Audio 2", link:'https://www.youtube.com/embed/UyRNxbR-B9w'}] },
    { surahId: 105, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/4C3FZjkIKKo` },{name:"Audio 2", link:'https://www.youtube.com/embed/PFI4ZBtsXr4'}] },
    { surahId: 106, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/wktEC7Jp5CU` },{name:"Audio 2", link:'https://www.youtube.com/embed/jCyWG2IAAKk'}] },
    { surahId: 107, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/l8VF5p4oPDE` },{name:"Audio 2", link:'https://www.youtube.com/embed/ULMPkx1_g7U'}] },
    { surahId: 108, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/gguAmbBNhJQ` },{name:"Audio 2", link:'https://www.youtube.com/embed/qGCxBeFpl0A'}] },
    { surahId: 109, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/4CvUCt_7t9Y` },{name:"Audio 2", link:'https://www.youtube.com/embed/t6viY2rkFdM'}] },
    { surahId: 110, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/MVE1Mozt23w` },{name:"Audio 2", link:'https://www.youtube.com/embed/JuskIaPO5Wg'}] },
    { surahId: 111, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/M3dBqRX32fI` },{name:"Audio 2", link:'https://www.youtube.com/embed/aYs5tIlN4l8'}] },
    { surahId: 112, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/fyub76Z1YW8` },{name:"Audio 2", link:'https://www.youtube.com/embed/N4diUcuNVic'}] },
    { surahId: 113, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/MaOepE0iVP0` },{name:"Audio 2", link:'https://www.youtube.com/embed/jEZZ4UX7d2A'}] },
    { surahId: 114, links: [{ name: 'Audio 1', link: `https://www.youtube.com/embed/5UTXy190B-I` },{name:"Audio 2", link:'https://www.youtube.com/embed/GVk5KmQKgAw'}] }       
];

export const onlineSurasMp3=[];
for(let i=1; i<=114; i++){

    let surahMp3=String(i).padStart(3, '0');
    const obj={
        surahId: i,
        links: [
            { id:'mishary', name: 'Mishari Al-afasi', link: `https://server8.mp3quran.net/afs/${surahMp3}.mp3` },
            { id:'maher', name: 'Maher Al Muaiqly', link: `https://server12.mp3quran.net/maher/${surahMp3}.mp3` },
            { id:'balila', name: 'Bandar Balila', link: `https://ia601409.us.archive.org/34/items/alfirdwsiy1433_gmail_0356835683568568356856802/${surahMp3}.mp3` },
            { id:'khalid', name: 'Khalid Al Jalil', link: `https://server10.mp3quran.net/jleel/${surahMp3}.mp3` },
            { id:'fareed', name: 'Hatem Fareed Al Waer', link: `https://server11.mp3quran.net/hatem/${surahMp3}.mp3` },
            { id:'khalifa', name: 'Khalifa Al Tunaiji', link: `https://server12.mp3quran.net/tnjy/${surahMp3}.mp3` },
            { id:'ghamdi', name: 'Saad Al Ghamdi', link: `https://server7.mp3quran.net/s_gmd/${surahMp3}.mp3` },
            { id:'shuraim', name: 'Saud Al Shuraim', link: `https://server7.mp3quran.net/shur/${surahMp3}.mp3` },
            { id:'shatri', name: 'Al Shatri', link: `https://server11.mp3quran.net/shatri/${surahMp3}.mp3` },
            { id:'bukhatir', name: 'Salah Bukhatir', link: `https://server8.mp3quran.net/bu_khtr/${surahMp3}.mp3` },
            
        ]                 
    }
    onlineSurasMp3.push(obj);
}  