export const ALLAH_NAMES = [
    { arabic: "الرَّحْمَنُ", english: "Ar-Rahman", meaning: "The Most Compassionate" },
    { arabic: "الرَّحِيمُ", english: "Ar-Rahim", meaning: "The Most Merciful" },
    { arabic: "الْمَلِكُ", english: "Al-Malik", meaning: "The Absolute Ruler" },
    { arabic: "الْقُدُّوسُ", english: "Al-Quddus", meaning: "The Pure One" },
    { arabic: "السَّلاَمُ", english: "As-Salam", meaning: "The Source of Peace" },
    { arabic: "الْمُؤْمِنُ", english: "Al-Mu'min", meaning: "Giver of Faith and Security" },
    { arabic: "الْمُهَيْمِنُ", english: "Al-Muhaymin", meaning: "The Protector" },
    { arabic: "الْعَزِيزُ", english: "Al-Aziz", meaning: "The Almighty" },
    { arabic: "الْجَبَّارُ", english: "Al-Jabbar", meaning: "The Compeller" },
    { arabic: "الْمُتَكَبِّرُ", english: "Al-Mutakabbir", meaning: "The Majestic, the Supremely Great" },
    { arabic: "الْخَالِقُ", english: "Al-Khaliq", meaning: "The Creator" },
    { arabic: "الْبَارِئُ", english: "Al-Bari'", meaning: "The Evolver" },
    { arabic: "الْمُصَوِّرُ", english: "Al-Musawwir", meaning: "The Fashioner" },
    { arabic: "الْغَفَّارُ", english: "Al-Ghaffar", meaning: "The Constant Forgiver" },
    { arabic: "الْقَهَّارُ", english: "Al-Qahhar", meaning: "The All-Subduer" },
    { arabic: "الْوَهَّابُ", english: "Al-Wahhab", meaning: "The Supreme Bestower" },
    { arabic: "الرَّزَّاقُ", english: "Ar-Razzaq", meaning: "The Provider" },
    { arabic: "الْفَتَّاحُ", english: "Al-Fattah", meaning: "The Supreme Opener" },
    { arabic: "اَلْعَلِيمُ", english: "Al-Alim", meaning: "The All-Knowing" },
    { arabic: "الْقَابِضُ", english: "Al-Qabid", meaning: "The Withholder" },
    { arabic: "الْبَاسِطُ", english: "Al-Basit", meaning: "The Extender" },
    { arabic: "الْخَافِضُ", english: "Al-Khafid", meaning: "The Reducer" },
    { arabic: "الرَّافِعُ", english: "Ar-Rafi", meaning: "The Exalter" },
    { arabic: "الْمُعِزُّ", english: "Al-Mu'izz", meaning: "Bestower of Honour" },
    { arabic: "المُذِلُّ", english: "Al-Mudhill", meaning: "The Dishonourer" },
    { arabic: "السَّمِيعُ", english: "As-Sami", meaning: "All-Hearing" },
    { arabic: "الْبَصِيرُ", english: "Al-Basir", meaning: "All-Seeing" },
    { arabic: "الْحَكَمُ", english: "Al-Hakam", meaning: "The Impartial Judge" },
    { arabic: "الْعَدْلُ", english: "Al-Adl", meaning: "The Utterly Just" },
    { arabic: "اللَّطِيفُ", english: "Al-Latif", meaning: "The Subtle One" },
    { arabic: "الْخَبِيرُ", english: "Al-Khabir", meaning: "All-Aware" },
    { arabic: "الْحَلِيمُ", english: "Al-Halim", meaning: "The Forbearing" },
    { arabic: "الْعَظِيمُ", english: "Al-Azim", meaning: "The Magnificent" },
    { arabic: "الْغَفُورُ", english: "Al-Ghafoor", meaning: "The Great Forgiver" },
    { arabic: "الشَّكُورُ", english: "Ash-Shakur", meaning: "The Most Appreciative" },
    { arabic: "الْعَلِيُّ", english: "Al-Aliyy", meaning: "The Most High" },
    { arabic: "الْكَبِيرُ", english: "Al-Kabir", meaning: "The Most Great" },
    { arabic: "الْحَفِيظُ", english: "Al-Hafiz", meaning: "Preserver" },
    { arabic: "المُقيت", english: "Al-Muqit", meaning: "Sustainer" },
    { arabic: "الْحسِيبُ", english: "Al-Hasib", meaning: "The Reckoner" },
    { arabic: "الْجَلِيلُ", english: "Al-Jalil", meaning: "The Majestic" },
    { arabic: "الْكَرِيمُ", english: "Al-Karim", meaning: "The Most Generous" },
    { arabic: "الرَّقِيبُ", english: "Ar-Raqib", meaning: "The Watchful" },
    { arabic: "الْمُجِيبُ", english: "Al-Mujib", meaning: "Responder" },
    { arabic: "الْوَاسِعُ", english: "Al-Wasi", meaning: "The All-Encompassing" },
    { arabic: "الْحَكِيمُ", english: "Al-Hakim", meaning: "The All-Wise" },
    { arabic: "الْوَدُودُ", english: "Al-Wadud", meaning: "Most Loving" },
    { arabic: "الْمَجِيدُ", english: "Al-Majid", meaning: "Glorious" },
    { arabic: "الْبَاعِثُ", english: "Al-Ba'ith", meaning: "The Infuser of New Life" },
    { arabic: "الشَّهِيدُ", english: "Ash-Shahid", meaning: "The All Observing Witness" },
    { arabic: "الْحَقُّ", english: "Al-Haqq", meaning: "The Absolute Truth" },
    { arabic: "الْوَكِيلُ", english: "Al-Wakil", meaning: "The Trustee, Disposer of Affairs" },
    { arabic: "الْقَوِيُّ", english: "Al-Qawiyy", meaning: "The All-Strong" },
    { arabic: "الْمَتِينُ", english: "Al-Matin", meaning: "The Firm One" },
    { arabic: "الْوَلِيُّ", english: "Al-Waliyy", meaning: "Protecting Associate" },
    { arabic: "الْحَمِيدُ", english: "Al-Hamid", meaning: "The Praiseworthy" },
    { arabic: "الْمُحْصِي", english: "Al-Muhsi", meaning: "The All-Enumerating, Originator" },
    { arabic: "الْمُبْدِئُ", english: "Al-Mubdi'", meaning: "The Originator" },
    { arabic: "الْمُعِيدُ", english: "Al-Mu'id", meaning: "The Restorer" },
    { arabic: "الْمُحْيِي", english: "Al-Muhyi", meaning: "The Giver of Life" },
    { arabic: "الْمُمِيتُ", english: "Al-Mumit", meaning: "The Creator of Death" },
    { arabic: "الْحَيُّ", english: "Al-Hayy", meaning: "The Ever-Living" },
    { arabic: "الْقَيُّومُ", english: "Al-Qayyum", meaning: "The Sustainer" },
    { arabic: "الْوَاجِدُ", english: "Al-Wajid", meaning: "The Perceiver" },
    { arabic: "الْمَاجِدُ", english: "Al-Majid", meaning: "Glorious (alternate entry)" },
    { arabic: "الْواحِدُ", english: "Al-Wahid", meaning: "The One" },
    { arabic: "الصَّمَدُ", english: "As-Samad", meaning: "Self-Sufficient" },
    { arabic: "الْقَادِرُ", english: "Al-Qadir", meaning: "The All-Capable" },
    { arabic: "الْمُقْتَدِرُ", english: "Al-Muqtadir", meaning: "The Creator of All Power" },
    { arabic: "الْمُقَدِّمُ", english: "Al-Muqaddim", meaning: "Expeditor" },
    { arabic: "الْمُؤَخِّرُ", english: "Al-Mu'akhkhir", meaning: "Delayer" },
    { arabic: "الأَوَّلُ", english: "Al-Awwal", meaning: "The First" },
    { arabic: "الْآخِرُ", english: "Al-Akhir", meaning: "The Last" },
    { arabic: "الظَّاهِرُ", english: "Az-Zahir", meaning: "The Manifest One" },
    { arabic: "الْبَاطِنُ", english: "Al-Batin", meaning: "The Hidden One" },
    { arabic: "الْوَالِي", english: "Al-Wali", meaning: "Sole Controller" },
    { arabic: "الْمُتَعَالِي", english: "Al-Muta'ali", meaning: "Self Exalted" },
    { arabic: "الْبَرُّ", english: "Al-Barr", meaning: "The Source of All Goodness" },
    { arabic: "التَّوَّابُ", english: "At-Tawwab", meaning: "Ever-Accepter of Repentance" },
    { arabic: "الْمُنْتَقِمُ", english: "Al-Muntaqim", meaning: "Avenger" },
    { arabic: "العَفُوُّ", english: "Al-'Afuww", meaning: "The Supreme Pardoner" },
    { arabic: "الرَّؤُوفُ", english: "Ar-Ra'uf", meaning: "Most Kind" },
    { arabic: "مَالِكُ الْمُلْكِ", english: "Malik-ul-Mulk", meaning: "Owner of All" },
    { arabic: "ذُو الْجَلَالِ وَالإكْرَامِ", english: "Dhul-Jalaali Wal-Ikram", meaning: "Lord of Glory and Honour" },
    { arabic: "الْمُقْسِطُ", english: "Al-Muqsit", meaning: "The Just One" },
    { arabic: "الْجَامِعُ", english: "Al-Jami'", meaning: "Gatherer" },
    { arabic: "الْغَنِيُّ", english: "Al-Ghaniyy", meaning: "Self-Sufficient, Wealthy" },
    { arabic: "الْمُغْنِي", english: "Al-Mughni", meaning: "Enricher" },
    { arabic: "الْمَانِعُ", english: "Al-Mani'", meaning: "Withholder" },
    { arabic: "الضَّارُ", english: "Ad-Darr", meaning: "Distresser" },
    { arabic: "النَّافِعُ", english: "An-Nafi'", meaning: "Propitious, Benefactor" },
    { arabic: "النُّورُ", english: "An-Nur", meaning: "Light" },
    { arabic: "الْهَادِي", english: "Al-Hadi", meaning: "The Guide" },
    { arabic: "الْبَدِيعُ", english: "Al-Badi'", meaning: "Originator, Incomparable" },
    { arabic: "الْبَاقِي", english: "Al-Baqi", meaning: "Everlasting" },
    { arabic: "الْوَارِثُ", english: "Al-Warith", meaning: "Inheritance" },
    { arabic: "الرَّشِيدُ", english: "Ar-Rashid", meaning: "Righteous Teacher" },
    { arabic: "الصَّبُورُ", english: "As-Sabur", meaning: "The Patient One" }
  ];