export const ALLAH_NAMES = [
  {"arabic":"ٱلرَّحْمَٰنُ","english":"Ar-Raḥmān","meaning":"The Most or Entirely Merciful"},
  {"arabic":"ٱلرَّحِيمُ","english":"Ar-Raḥīm","meaning":"The Especially Merciful"},
  {"arabic":"ٱلْمَلِكُ","english":"Al-Malik","meaning":"The King and Owner of Dominion"},
  {"arabic":"ٱلْقُدُّوسُ","english":"Al-Quddūs","meaning":"The Absolutely Pure and Perfect"},
  {"arabic":"ٱلسَّلَامُ","english":"As-Salām","meaning":"The Perfection and Giver of Peace"},
  {"arabic":"ٱلْمُؤْمِنُ","english":"Al-Mu’min","meaning":"The Granter of Security and Faith"},
  {"arabic":"ٱلْمُهَيْمِنُ","english":"Al-Muhaymin","meaning":"The Guardian, The Witness, The Overseer"},
  {"arabic":"ٱلْعَزِيزُ","english":"Al-‘Azīz","meaning":"The Almighty, The All-Powerful, The Invincible, The Honorable"},
  {"arabic":"ٱلْجَبَّارُ","english":"Al-Jabbār","meaning":"The Compeller, The Restorer"},
  {"arabic":"ٱلْمُتَكَبِّرُ","english":"Al-Mutakabbir","meaning":"The Supreme, The Majestic"},
  {"arabic":"ٱلْخَٰلِقُ","english":"Al-Khāliq","meaning":"The Creator, The Maker"},
  {"arabic":"ٱلْبَارِئُ","english":"Al-Bāriʾ","meaning":"The Originator, The Inventor"},
  {"arabic":"ٱلْمُصَوِّرُ","english":"Al-Muṣawwir","meaning":"The Fashioner, The Shaper"},
  {"arabic":"ٱلْغَفَّارُ","english":"Al-Ghaffār","meaning":"The Constant Forgiver, The Great Forgiver"},
  {"arabic":"ٱلْقَهَّارُ","english":"Al-Qahhār","meaning":"The Subduer, The Ever-Dominating"},
  {"arabic":"ٱلْوَهَّابُ","english":"Al-Wahhāb","meaning":"The Giver of Gifts, The Bestower"},
  {"arabic":"ٱلرَّزَّاقُ","english":"Ar-Razzāq","meaning":"The Ever-Providing, The Constant Provider"},
  {"arabic":"ٱلْفَتَّاحُ","english":"Al-Fattāḥ","meaning":"The Opener, The Judge"},
  {"arabic":"ٱلْعَلِيمُ","english":"Al-ʿAlīm","meaning":"The All-Knowing, The Omniscient"},
  {"arabic":"ٱلْقَابِضُ","english":"Al-Qābiḍ","meaning":"The Withholder, The Restrainer"},
  {"arabic":"ٱلْبَاسِطُ","english":"Al-Bāsiṭ","meaning":"The Extender, The Expander"},
  {"arabic":"ٱلْخَافِضُ","english":"Al-Khāfiḍ","meaning":"The Reducer, The Abaser"},
  {"arabic":"ٱلرَّافِعُ","english":"Ar-Rāfiʿ","meaning":"The Exalter, The Elevator"},
  {"arabic":"ٱلْمُعِزُّ","english":"Al-Muʿizz","meaning":"The Honourer, The Bestower of Honor"},
  {"arabic":"ٱلْمُذِلُّ","english":"Al-Mudhill","meaning":"The Dishonourer, The Humiliator"},
  {"arabic":"ٱلسَّمِيعُ","english":"As-Samīʿ","meaning":"The All-Hearing"},
  {"arabic":"ٱلْبَصِيرُ","english":"Al-Baṣīr","meaning":"The All-Seeing"},
  {"arabic":"ٱلْحَكَمُ","english":"Al-Ḥakam","meaning":"The Judge, The Giver of Justice"},
  {"arabic":"ٱلْعَدْلُ","english":"Al-‘Adl","meaning":"The Utterly Just"},
  {"arabic":"ٱللَّطِيفُ","english":"Al-Laṭīf","meaning":"The Most Gentle, The Subtle One"},
  {"arabic":"ٱلْخَبِيرُ","english":"Al-Khabīr","meaning":"The All-Aware, The All-Acquainted"},
  {"arabic":"ٱلْحَلِيمُ","english":"Al-Ḥalīm","meaning":"The Most Forbearing"},
  {"arabic":"ٱلْعَظِيمُ","english":"Al-ʿAẓīm","meaning":"The Magnificent, The Supreme"},
  {"arabic":"ٱلْغَفُورُ","english":"Al-Ghafūr","meaning":"The Forgiving, The Exceedingly Forgiving"},
  {"arabic":"ٱلشَّكُورُ","english":"Ash-Shakūr","meaning":"The Most Appreciative"},
  {"arabic":"ٱلْعَلِيُّ","english":"Al-ʿAlī","meaning":"The Most High, The Exalted"},
  {"arabic":"ٱلْكَبِيرُ","english":"Al-Kabīr","meaning":"The Greatest, The Most Grand"},
  {"arabic":"ٱلْحَفِيظُ","english":"Al-Ḥafīẓ","meaning":"The Preserver, The All-Heedful and All-Protecting"},
  {"arabic":"ٱلْمُقِيتُ","english":"Al-Muqīt","meaning":"The Sustainer, The Maintainer"},
  {"arabic":"ٱلْحَسِيبُ","english":"Al-Ḥasīb","meaning":"The Reckoner"},
  {"arabic":"ٱلْجَلِيلُ","english":"Al-Jalīl","meaning":"The Majestic"},
  {"arabic":"ٱلْكَرِيمُ","english":"Al-Karīm","meaning":"The Most Generous, The Most Noble"},
  {"arabic":"ٱلرَّقِيبُ","english":"Ar-Raqīb","meaning":"The Watchful, The All-Watchful"},
  {"arabic":"ٱلْمُجِيبُ","english":"Al-Mujīb","meaning":"The Responsive, The Answerer"},
  {"arabic":"ٱلْوَاسِعُ","english":"Al-Wāsiʿ","meaning":"The All-Encompassing, the Boundless"},
  {"arabic":"ٱلْحَكِيمُ","english":"Al-Ḥakīm","meaning":"The All-Wise"},
  {"arabic":"ٱلْوَدُودُ","english":"Al-Wadūd","meaning":"The Most Loving"},
  {"arabic":"ٱلْمَجِيدُ","english":"Al-Majīd","meaning":"The Glorious, The Most Honorable"},
  {"arabic":"ٱلْبَاعِثُ","english":"Al-Bāʿith","meaning":"The Infuser of New Life, The Resurrector"},
  {"arabic":"ٱلشَّهِيدُ","english":"As-Shahīd","meaning":"The All-Witnessing"},
  {"arabic":"ٱلْحَقُّ","english":"Al-Ḥaqq","meaning":"The Absolute Truth"},
  {"arabic":"ٱلْوَكِيلُ","english":"Al-Wakīl","meaning":"The Trustee, The Disposer of Affairs"},
  {"arabic":"ٱلْقَوِيُّ","english":"Al-Qawiyy","meaning":"The All-Strong"},
  {"arabic":"ٱلْمَتِينُ","english":"Al-Matīn","meaning":"The Firm, The Steadfast"},
  {"arabic":"ٱلْوَلِيُّ","english":"Al-Waliyy","meaning":"The Protector, The Guardian"},
  {"arabic":"ٱلْحَمِيدُ","english":"Al-Ḥamīd","meaning":"The Praiseworthy, The Most Praised"},
  {"arabic":"ٱلْمُحْصِي","english":"Al-Muḥṣī","meaning":"The All-Enumerating, The Counter"},
  {"arabic":"ٱلْمُبْدِئُ","english":"Al-Mubdiʾ","meaning":"The Originator, The Initiator"},
  {"arabic":"ٱلْمُعِيدُ","english":"Al-Muʿīd","meaning":"The Restorer, The Reinstater"},
  {"arabic":"ٱلْمُحْيِي","english":"Al-Muḥyī","meaning":"The Giver of Life"},
  {"arabic":"ٱلْمُمِيتُ","english":"Al-Mumīt","meaning":"The Creator of Death"},
  {"arabic":"ٱلْحَيُّ","english":"Al-Ḥayy","meaning":"The Ever-Living"},
  {"arabic":"ٱلْقَيُّومُ","english":"Al-Qayyūm","meaning":"The Sustainer, The Self-Subsisting"},
  {"arabic":"ٱلْوَاجِدُ","english":"Al-Wājid","meaning":"The Finder, The Perceiver"},
  {"arabic":"ٱلْمَاجِدُ","english":"Al-Mājid","meaning":"The Illustrious, The Magnificent"},
  {"arabic":"ٱلْوَاحِدُ","english":"Al-Wāḥid","meaning":"The One, The Indivisible"},
  {"arabic":"ٱلْأَحَدُ","english":"Al-Aḥad","meaning":"The Unique, The Only One"},
  {"arabic":"ٱلصَّمَدُ","english":"Aṣ-Ṣamad","meaning":"The Eternal, The Absolute"},
  {"arabic":"ٱلْقَادِرُ","english":"Al-Qādir","meaning":"The Omnipotent, The All-Able"},
  {"arabic":"ٱلْمُقْتَدِرُ","english":"Al-Muqtadir","meaning":"The All-Powerful, The Dominant"},
  {"arabic":"ٱلْمُقَدِّمُ","english":"Al-Muqaddim","meaning":"The Expediter, The Promoter"},
  {"arabic":"ٱلْمُؤَخِّرُ","english":"Al-Muʾakhkhir","meaning":"The Delayer, The Postponer"},
  {"arabic":"ٱلْأَوَّلُ","english":"Al-Awwal","meaning":"The First, The Foremost"},
  {"arabic":"ٱلْآخِرُ","english":"Al-Ākhir","meaning":"The Last, The Utmost"},
  {"arabic":"ٱلظَّاهِرُ","english":"Aẓ-Ẓāhir","meaning":"The Manifest, The All-Surpassing"},
  {"arabic":"ٱلْبَاطِنُ","english":"Al-Bāṭin","meaning":"The Hidden One, Knower of the Hidden"},
  {"arabic":"ٱلْوَالِي","english":"Al-Wālī","meaning":"The Sole Governor"},
  {"arabic":"ٱلْمُتَعَالِي","english":"Al-Mutaʿālī","meaning":"The Self-Exalted"},
  {"arabic":"ٱلْبَرُّ","english":"Al-Barr","meaning":"The Source of All Goodness"},
  {"arabic":"ٱلتَّوَابُ","english":"At-Tawwāb","meaning":"The Ever-Pardoning"},
  {"arabic":"ٱلْمُنْتَقِمُ","english":"Al-Muntaqim","meaning":"The Avenger"},
  {"arabic":"ٱلْعَفُوُّ","english":"Al-ʿAfūw","meaning":"The Pardoner"},
  {"arabic":"ٱلرَّءُوفُ","english":"Ar-Raʾūf","meaning":"The Most Kind"},
  {"arabic":"مَالِكُ ٱلْمُلْكِ","english":"Mālik al-Mulk","meaning":"Master of the Dominion, Owner of the Kingdom"},
  {"arabic":"ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ","english":"Dhū al-Jalāli wa’l-Ikrām","meaning":"Possessor of Glory and Honour"},
  {"arabic":"ٱلْمُقْسِطُ","english":"Al-Muqsiṭ","meaning":"The Just One"},
  {"arabic":"ٱلْجَامِعُ","english":"Al-Jāmiʿ","meaning":"The Gatherer, the Uniter"},
  {"arabic":"ٱلْغَنِيُّ","english":"Al-Ghaniyy","meaning":"The Self-Sufficient, The Wealthy"},
  {"arabic":"ٱلْمُغْنِيُ","english":"Al-Mughnī","meaning":"The Enricher"},
  {"arabic":"ٱلْمَانِعُ","english":"Al-Māniʿ","meaning":"The Withholder"},
  {"arabic":"ٱلضَّارُّ","english":"Aḍ-Ḍārr","meaning":"The Distresser"},
  {"arabic":"ٱلنَّافِعُ","english":"An-Nāfiʿ","meaning":"The Propitious, The Benefactor"},
  {"arabic":"ٱلنُّورُ","english":"An-Nūr","meaning":"The Light"},
  {"arabic":"ٱلْهَادِي","english":"Al-Hādī","meaning":"The Guide"},
  {"arabic":"ٱلْبَدِيعُ","english":"Al-Badīʿ","meaning":"The Incomparable Originator"},
  {"arabic":"ٱلْبَاقِي","english":"Al-Bāqī","meaning":"The Ever-Lasting"},
  {"arabic":"ٱلْوَارِثُ","english":"Al-Wāriṯ","meaning":"The Inheritor"},
  {"arabic":"ٱلرَّشِيدُ","english":"Ar-Rashīd","meaning":"The Guide to the Right Path"},
  {"arabic":"ٱلصَّبُورُ","english":"Aṣ-Ṣabūr","meaning":"The Patient"}
];